version: '3.8'

services:
  bank-analysis-backend:
    build:
      context: ./BankAnalysisCpp  # Path to the directory containing the Dockerfile for service1
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Maps port 8080 on the host to port 8080 inside the container
    networks:
      - bank-nw
    volumes:
      - ./config/categories.json:/app/categories.json

  bank-analysis-react:
    build:
      context: ./bank_analysis_react # Path to the directory containing the docker file for the react project
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Maps port 3000 on the host to port 3000 inside the container
    networks:
      - bank-nw
    volumes:
      - ./config/frontendConfig.json:/app/public/frontendConfig.json

networks:
  bank-nw:  # Defines a custom network so the services can communicate with each other
    driver: bridge
